version: "3.9"

services:
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: app
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U symfony"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      APP_ENV: dev
      DATABASE_URL: postgresql://symfony:symfony@db:5432/app?serverVersion=13&charset=utf8
      MERCURE_URL: http://mercure/.well-known/mercure
      MERCURE_PUBLIC_URL: http://mercure/.well-known/mercure
      MERCURE_JWT_SECRET: "!ChangeMe!"
    volumes:
      - ./api:/var/www/html:cached
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "php -v || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    image: node:20-alpine
    working_dir: /app
    environment:
      # Expose Next.js dev server on 3000 for Caddy
      PORT: 3000
      HOSTNAME: 0.0.0.0
      # API URL pour les appels côté client (via Caddy)
      NEXT_PUBLIC_API_URL: http://localhost/api
    command: sh -c "yarn dev"
    volumes:
      - ./web:/app:cached
    healthcheck:
      test: ["CMD-SHELL", "node -v && [ -f package.json ]"]
      interval: 10s
      timeout: 5s
      retries: 10


  mercure:
    image: node:20-alpine
    working_dir: /app
    command: node mercure-server.js
    volumes:
      - ./mercure-server.js:/app/mercure-server.js:ro

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./api:/srv/api:ro
    depends_on:
      api:
        condition: service_healthy
      web:
        condition: service_started
      mercure:
        condition: service_started

volumes:
  db-data:
